services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    env_file:
      - ./.env
    ports:
      - '5432'
